import { spawn } from 'node:child_process';
import { once } from 'node:events';
import { mkdir, mkdtemp, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import openapiTS, { astToString } from 'openapi-typescript';
import { dotnetPath } from './dotnet-path.mjs';

const directory = await mkdtemp(join(tmpdir(), 'au2-contracts-'));
const child = spawn(
  dotnetPath(),
  ['run', '--project', 'src/Starter.Api', '--no-launch-profile', '--urls', 'http://127.0.0.1:0'],
  {
    env: {
      ...process.env,
      ASPNETCORE_ENVIRONMENT: 'Development',
      ConnectionStrings__Database: `Data Source=${join(directory, 'contracts.db')}`,
    },
    stdio: ['ignore', 'pipe', 'pipe'],
  },
);
let output = '';
child.stdout.on('data', (data) => {
  output += data;
});
child.stderr.on('data', (data) => {
  output += data;
});
let spawnError;
child.on('error', (error) => {
  spawnError = error;
});
for (const signal of ['SIGINT', 'SIGTERM']) process.on(signal, () => child.kill(signal));

try {
  let schema;
  for (let attempt = 0; attempt < 120; attempt++) {
    if (spawnError || child.exitCode !== null)
      throw new Error(output || spawnError?.message || 'API exited.');
    try {
      const address = output.match(/Now listening on: (http:\/\/127\.0\.0\.1:\d+)/)?.[1];
      if (!address) throw new Error('Waiting for API address.');
      const response = await fetch(`${address}/openapi/v1.json`, {
        signal: AbortSignal.timeout(1000),
      });
      if (response.ok) {
        schema = await response.json();
        break;
      }
    } catch {
      /* The API is still starting. */
    }
    await new Promise((resolve) => setTimeout(resolve, 500));
  }
  if (!schema) throw new Error(`API did not become ready.\n${output}`);
  const types = astToString(await openapiTS(schema));
  const destination = 'src/Starter.Web/src/api/generated';
  await mkdir(destination, { recursive: true });
  await writeFile(
    `${destination}/schema.d.ts`,
    `// Generated by npm run api:types. Do not edit.\n${types}`,
  );
  console.log('Updated API contracts.');
} finally {
  if (child.exitCode === null && !spawnError) {
    const stopped = once(child, 'exit');
    child.kill('SIGTERM');
    await stopped;
  }
  await rm(directory, { recursive: true, force: true });
}
